require_relative 'ec2/host/version'
require_relative 'ec2/host/string_util'
require_relative 'ec2/host/hash_util'
require_relative 'ec2/host/config'
require_relative 'ec2/host/host_data'
require_relative 'ec2/host/role_data'
require_relative 'ec2/host/ec2_client'
require_relative 'ec2/host'
